### ISSUE TITLE
[Python] Can't install on Raspberry Pi (Failed building wheel for pyarrow)

### ISSUE THREAD

**Issue by vmalisz** [apache/arrow#33814]
### Describe the bug, including details regarding any error messages, version, and platform.

I tried to install pyarrow via pip and from the source following those instructions here https://arrow.apache.org/docs/developers/python.html#python-development 

both methods showed the same errors. The output of the pip command is attached. 
[pipout.txt](https://github.com/apache/arrow/files/10471704/pipout.txt)

Same results on Buster and Bullseye, Python 3.7

I also found a very similar issue here and tried to follow the steps with no success https://github.com/apache/arrow/issues/14920

any suggestions for me to try?
thank you!

### Component(s)

Python

**Comment by kou** [comment]
It seems that you didn't define `CMAKE_PREFIX_PATH`:

https://arrow.apache.org/docs/dev/developers/python.html#using-system-and-bundled-dependencies

```bash
export ARROW_HOME=$(pwd)/dist
export LD_LIBRARY_PATH=$(pwd)/dist/lib:$LD_LIBRARY_PATH
export CMAKE_PREFIX_PATH=$ARROW_HOME:$CMAKE_PREFIX_PATH
```

**Comment by vmalisz** [comment]
thank you for your quick answer. I have another error now: No module named 'cmake' (output: 
[pipout_2.txt](https://github.com/apache/arrow/files/10472400/pipout_2.txt) )

It is installed already and I double-checked 'import cmake' in a Python terminal it worked.

**Comment by vmalisz** [comment]
I realized I didn't have the last version for pip, I just upgraded to pip 22.3.1 but it didn't change the result

**Comment by westonpace** [comment]
When you tried `import cmake` in the terminal were you using this python executable? `/home/pi/pyarrow-dev/bin/python3`

**Comment by vmalisz** [comment]
'which python3' gives me that path yes
/home/pi/pyarrow-dev/bin/python3

**Comment by kou** [comment]
What is `/home/pi/.local/bin/cmake`?

Could you show `file /home/pi/.local/bin/cmake` and `head /home/pi/.local/bin/cmake`?

How did you install CMake? `pip install cmake`? ( https://pypi.org/project/cmake/ ?)

**Comment by vmalisz** [comment]
I did install cmake via pip (also tried to uninstall and install again)

.local/bin because I didn't run the install from the virtualenv this time,  not sure why it's .local though, I'd have expected usr/bin but that's probably another story!
The error is the same anyways; that's why I didn't notice, sorry bout the confusion. 
Here's the output from the same virtual env from before: 
[out.txt](https://github.com/apache/arrow/files/10473194/out.txt) 

+ the information requested: (same for /home/pi/pyarrow-dev/bin/cmake)
$ file /home/pi/.local/bin/cmake
`/home/pi/.local/bin/cmake: Python script, ASCII text executable`

$ head /home/pi/.local/bin/cmake
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from cmake import cmake
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cmake())
```

**Comment by kou** [comment]
OK. Could you show `head /home/pi/pyarrow-dev/bin/cmake`?
I think the shebang of the file is wrong. It must be `#!/home/pi/pyarrow-dev/bin/python3`.

**Comment by vmalisz** [comment]
it looks good
 
$ head /home/pi/pyarrow-dev/bin/cmake
```
#!/home/pi/pyarrow-dev/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from cmake import cmake
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cmake())
```

**Comment by kou** [comment]
Does `/home/pi/pyarrow-dev/bin/cmake --help` work?

**Comment by vmalisz** [comment]
it does

**Comment by kou** [comment]
Could you use CMake installed by `apt` not `pip` or try `pip install --no-build-isolation pyarrow`?

**Comment by vmalisz** [comment]
`pip install --no-build-isolation pyarrow` 
[pip-nobuild-out.txt](https://github.com/apache/arrow/files/10473550/pip-nobuild-out.txt)

not sure how to use the apt cmake instead of pip? 
I did 
`pip uninstall cmake`

but 'sudo apt install cmake' didn't work:
`Reading package lists... Done
Building dependency tree
Reading state information... Done
cmake is already the newest version (3.16.3-3~bpo10+1).
The following packages were automatically installed and are no longer required:
  docutils-common libpython-all-dev lxplug-volume mypy pylint3 python-all-dev python-configparser python-entrypoints python-keyring python-keyrings.alt python-secretstorage python-wheel
  python-xdg python3-astroid python3-asttokens python3-docutils python3-isort python3-jedi python3-lazy-object-proxy python3-logilab-common python3-mccabe python3-mypy
  python3-mypy-extensions python3-parso python3-roman python3-send2trash python3-typed-ast python3-wrapt sgml-base xml-core xsel
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

`which cmake` indicates the one used by the main profile
`/home/pi/.local/bin/cmake`

**Comment by kou** [comment]
Ah, we need to install build dependencies manually with `pip install --no-build-isolation`:

```bash
wget https://raw.githubusercontent.com/apache/arrow/master/python/requirements-build.txt
pip install -r requirements-build.txt
pip install --no-build-isolation pyarrow
```

I think that you can remove `/home/pi/.local/bin/cmake` by `/usr/bin/python3 -m pip uninstall cmake`.

**Comment by vmalisz** [comment]
indeed. it finally removed that confusing .local, no idea where it came from...  it's now using cmake from /usr/bin/
I did:
`sudo apt remove cmake` (success!)
`sudo apt install cmake` (success!)
`pip install pyarrow` goes back to the CMAKE_PREFIX_PATH error. I tried to redefine it as explained [above](https://github.com/apache/arrow/issues/33814#issuecomment-1399201865) guessing the uninstall might have wiped it, with no success. output: 
[out-with-aptcmake.txt](https://github.com/apache/arrow/files/10473595/out-with-aptcmake.txt)

Thanks for explaining the no-build (and for the rest too of course!) I still only have a basic understanding of all those processes.

here's the output for it: [nobuild-output.txt](https://github.com/apache/arrow/files/10473605/nobuild-output.txt)

**Comment by kou** [comment]
How did you install Apache Arrow C++? Could you show complete command lines?

**Comment by vmalisz** [comment]
I followed exactly the instructions here: https://arrow.apache.org/docs/dev/developers/python.html#using-system-and-bundled-dependencies

`git clone https://github.com/apache/arrow.git`

`pushd arrow
git submodule update --init
export PARQUET_TEST_DATA="${PWD}/cpp/submodules/parquet-testing/data"
export ARROW_TEST_DATA="${PWD}/testing/data"
popd`

`sudo apt-get install build-essential cmake python3-dev`

`python3 -m venv pyarrow-dev
source ./pyarrow-dev/bin/activate
pip install -r arrow/python/requirements-build.txt

# This is the folder where we will install the Arrow libraries during
# development
mkdir dist

(forgot that part below initially)
`export ARROW_HOME=$(pwd)/dist
export LD_LIBRARY_PATH=$(pwd)/dist/lib:$LD_LIBRARY_PATH
export CMAKE_PREFIX_PATH=$ARROW_HOME:$CMAKE_PREFIX_PATH`

the error happened here at 'make install'
`mkdir arrow/cpp/build
pushd arrow/cpp/build
cmake -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE=Debug \
        -DARROW_BUILD_TESTS=ON \
        -DARROW_COMPUTE=ON \
        -DARROW_CSV=ON \
        -DARROW_DATASET=ON \
        -DARROW_FILESYSTEM=ON \
        -DARROW_HDFS=ON \
        -DARROW_JSON=ON \
        -DARROW_PARQUET=ON \
        -DARROW_WITH_BROTLI=ON \
        -DARROW_WITH_BZ2=ON \
        -DARROW_WITH_LZ4=ON \
        -DARROW_WITH_SNAPPY=ON \
        -DARROW_WITH_ZLIB=ON \
        -DARROW_WITH_ZSTD=ON \
        -DPARQUET_REQUIRE_ENCRYPTION=ON \
        ..
make -j4
make install
popd`

trying again with https://arrow.apache.org/docs/dev/developers/cpp/building.html#cpp-building-building

some confusion here tbh: 
- cmake I had installed with apt was 3.18 so I couldn't use --preset (available for version >3.21)
- I install ($ make install) 3.25.2 from the [source](https://github.com/Kitware/CMake/releases/download/v3.25.2/cmake-3.25.2.tar.gz)
- cmake --version didn't work as if cmake was not installed
- I end up doing apt install again. it says 3.18 is being installed but cmake --version now says 3.25
... anyways, moving on:

`$ cmake .. --preset ninja-debug-minimal` worked

```
$ tree debug
debug/
├── libarrow_dataset.so -> libarrow_dataset.so.1100
├── libarrow_dataset.so.1100 -> libarrow_dataset.so.1100.0.0
├── libarrow_dataset.so.1100.0.0
├── libarrow.so -> libarrow.so.1100
├── libarrow.so.1100 -> libarrow.so.1100.0.0
├── libarrow.so.1100.0.0
├── libparquet.so -> libparquet.so.1100
├── libparquet.so.1100 -> libparquet.so.1100.0.0
└── libparquet.so.1100.0.0

0 directories, 9 files
```
that part is a bit over my head, and I'm not sure where to go from there. Thanks again for your help!

**Comment by kou** [comment]
It seems that `export ARROW_HOME=...` is missing.
Could you show `echo $CMAKE_PREFIX_PATH`?
Could you also show `make install` output?

**Comment by vmalisz** [comment]
just ran
```
cmake --preset=ninja-release-python-minimal .
cmake --build .
sudo cmake --build . --target install
```
without errors.

Then tried to install pyarrow again and it worked!

I have no idea what I did honestly... it looks like pip can't work for a Pi installation. it requires the latest cmake from apt and for arrow to be compiled from the source. I have a limited understanding of that part, and still not sure why I still had to do a pip install on top of the build.

```
$ echo $CMAKE_PREFIX_PATH
/home/pi/dist:/home/pi/dist:
```

I don't know if I can run again `make install` now it works? (really afraid to break something...)

**Comment by vmalisz** [comment]
Let me know if I can help to resolve the vanilla pip install process for Raspberry, looks like a niche but it didn't work for me on 2 different set up so I guess it is really something that can be fixed. or I'm very unlucky

thank you again for your help, I can get back to my project! (and sleeping)

**Comment by kou** [comment]
`DESTDIR=/tmp/test/ make install` is safer but it's not needed because your problem was solved. :-)

I think that documented command lines work well but there are many command lines. So some human errors can be injected like `CMAKE_PREFIX_PATH`.
If we provide pyarrow wheels for Raspberry Pi, you just need to run `pip install pyarrow`.
We provide pyarrow wheels for aarch64: https://pypi.org/project/pyarrow/#files
I don't know what architecture is required for Raspberry Pi.

BTW, can we close this issue?

**Comment by vmalisz** [comment]
yes, I just did. Thank you again for your help!

**Comment by vmalisz** [comment]
hi @kou! I'm experiencing a new issue but note sure how related to the install it is so I dont want to create a new thread unless you tell me so.

I initially needed to install pyarrow because I couldn't install db-dtypes without it. Now I have both and it's confirmed if I try `pip install db-dtypes`

It looks like the issue is still with pyarrow though:
` import pyarrow.lib as _lib
ImportError: libarrow_dataset.so.1100: cannot open shared object file: No such file or directory`

the full error (worth mentioning the script works well on my laptop... maybe I should just consider not using a Pi for that project):
`Traceback (most recent call last):
  File "/home/pi/pyarrow-dev/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 41, in <module>
    import db_dtypes  # type: ignore
  File "/home/pi/pyarrow-dev/lib/python3.7/site-packages/db_dtypes/__init__.py", line 26, in <module>
    import pyarrow
  File "/home/pi/pyarrow-dev/lib/python3.7/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: libarrow_dataset.so.1100: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_gscpull.py", line 5, in <module>
    gscdatapull(backfill=5)#, end_date='2022-11-10')
  File "/home/pi/gsc-bigquery/class_gscdailypull.py", line 22, in __init__
    self.do_allthethings(all_users_settings,self.backfill)
  File "/home/pi/gsc-bigquery/class_gscdailypull.py", line 58, in do_allthethings
    mydata = GSC(domain=domain,wp_user_id=user_data['user_id'],backfill=backfill, refresh=user_data['refresh_token'], end_date=self.end_date)
  File "/home/pi/gsc-bigquery/class_gsc.py", line 47, in __init__
    self.db_dates_data = bigquery.checkdata(self.start_date, self.end_date).to_dataframe()
  File "/home/pi/pyarrow-dev/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 1993, in to_dataframe
    _pandas_helpers.verify_pandas_imports()
  File "/home/pi/pyarrow-dev/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 1006, in verify_pandas_imports
    raise ValueError(_NO_DB_TYPES_ERROR) from db_dtypes_import_exception
ValueError: Please install the 'db-dtypes' package to use this function.
`

**Comment by kou** [comment]
You need to use `ninja-release-python` or `ninja-release-python-maximum` preset to use `pyarrow.dataset`:

```bash
cmake --preset=ninja-release-python .
cmake --build .
sudo cmake --build . --target install
pip install pyarrow
```

**Comment by vmalisz** [comment]
`cmake --preset=ninja-release-python .` stopped somewhere in the middle

so I just tried to add dataset to the minimal install, but have the same error when running my script.  
`cmake -DARROW_BUILD_STATIC=OFF -DARROW_COMPUTE=ON -DARROW_CSV=ON -DARROW_FILESYSTEM=ON -DARROW_JSON=ON -DARROW_DATASET=ON  -DCMAKE_BUILD_TYPE=Release`

trying `cmake --preset=ninja-release-python .` again, will report the error

**Comment by kou** [comment]
Could you show the full log?

**Comment by vmalisz** [comment]
it worked this time. no error but the script still fails

here's the output for `sudo cmake --build . --target install`
[install.txt](https://github.com/apache/arrow/files/10506099/install.txt)

looks like the library is installed
`-- Installing: /usr/local/lib/libarrow_dataset.so.1100.0.0
-- Up-to-date: /usr/local/lib/libarrow_dataset.so.1100
-- Set runtime path of "/usr/local/lib/libarrow_dataset.so.1100.0.0" to ""
-- Up-to-date: /usr/local/lib/libarrow_dataset.so
-- Up-to-date: /usr/local/lib/cmake/ArrowDataset/ArrowDatasetConfig.cmake
-- Up-to-date: /usr/local/lib/cmake/ArrowDataset/ArrowDatasetConfigVersion.cmake`

I tried adding /usr/local/lib/ to the PATH but didn't work either.

**Comment by vmalisz** [comment]
ok that was most likely the LD_LIBRARY_PATH, I ran a `sudo ldconfig` and now it works. THANK YOU! (I learned a lot!)

**Comment by kou** [comment]
No problem. :-)

**Comment by bdod92** [comment]
Hi @vmalisz and @kou, I am running into the same errors that you described above. Would you be able to summarize the list of commands that you entered to get pyarrow to run? I'm having trouble discerning which steps were necessary and which ones caused more issues. Thank you in advance!

**Comment by kou** [comment]
What is your platform?

In general, https://arrow.apache.org/docs/dev/developers/python.html#building-on-linux-and-macos should work.
If it doesn't work, we should update our documentations.
